version: '3.5'

services:
  nats:
    image: nats
    ports:
      - "4222:4222"
    networks:
      - nats_network

  natsqueue:
    build: ./NatsQueue
    depends_on:
      - nats
    networks:
      - nats_network

  worker:
    build: ./Worker
    depends_on:
      - nats
    networks:
      - nats_network

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - nats
    networks:
      - nats_network

networks:
  nats_network:
    driver: bridge