version: "3.5"
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks:
      - nats

  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - nats
    depends_on:
      - nats

  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks:
      - nats
    depends_on:
      - nats

  publisher:
    build: ./pub
    networks:
      - nats
    depends_on:
      - nats
      - subscriber
      
  subscriber:
    build: ./sub
    scale: 2
    networks:
      - nats
    depends_on:
      - nats
    
  worker:
    build: ./Worker
    networks:
      - nats
    depends_on:
      - nats

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - nats
    depends_on:
      - nats
     
networks:
  nats:
    name: nats
